hello/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include('hello_web.urls')),
    path("isitnewyear/", include("newyear.url")),
    path("tasks/", include("tasks.urls"))
]

hello/hello_web/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    
]

hello/tasks/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
    path("", views.index, name='index'),
    path("add", views.add, name='add'),

]

hello/hello_web/models.py
from django.db import models

# Create your models here.

hello/newyear/models.py
from django.db import models

# Create your models here.

hello/tasks/models.py
from django.db import models

# Create your models here.

hello/hello_web/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello Web!!!")

hello/newyear/views.py
from django.shortcuts import render
from datetime import datetime

def index(request):
    n = datetime.now()
    return render(request, "newyear/index.html",{
        'newyear':n.month == 3 and n.day == 13
    })

hello/tasks/views.py
from django.shortcuts import render
from django import forms

class add_task(forms.Form):
    form = forms.CharField(label="Enter new task")

tasks = ['Blue', 'Green', 'Red']

def index(request):
    return render(request, 'task/index.html', {
        'tasks':tasks
    })

def add(request):
    return render(request, 'task/add.html', {
        'form':add_task()
    })

hello/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'newyear/style.css'%}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>It's New Year</title>
</head>
<body>
    {% if newyear%}
    <h1>YES</h1>
    {% else%}
    <h1>NO</h1>
    {% endif%}
</body>
</html>

hello/newyear/templates/task/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
</head>
<body>
    {% for task in tasks%}
    <ul>
        <li>
            task
        </li>
    </ul>
    {%endfor%}
</body>
</html>

hello/tasks/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
</head>
<body>
    {% block content%}
 
    {% endblock %}
</body>
</html>

hello/tasks/templates/task/add.html
{% extends 'layout.html'%}


{% block content%}
    <h1>Add Task</h1>
    <form action="" method="post">{% csrf_token %}
        {{form}}
        <input type="submit" value="Add Task">
    </form>

    <a href="{% url 'task:index' %}">Show all task</a>
{% endblock%}

hello/tasks/templates/task/index.html
{% extends 'layout.html'%}


{% block content%}

<h6>List Of Task</h6>
{% for task in tasks%}
<ul>
    <li>
        {{task}}
    </li>
</ul>
{% empty %}

<ul>
    <li>
        No Task Yet
    </li>
</ul>

{% endfor%}
<a href="{% url 'task:add' %}">Add Task</a>
{% endblock%}